SELECT nombre FROM producto;
SELECT nombre, precio FROM producto;
SELECT column_name FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'producto';
SELECT nombre, precio, ROUND(precio * 1.1, 2) FROM producto;
SELECT nombre AS 'product name', precio AS 'euros', ROUND(precio * 1.1, 2) AS 'dolars' FROM producto;
SELECT UPPER(nombre), precio FROM producto;
SELECT LOWER(nombre), precio FROM producto;
SELECT nombre, UPPER(LEFT(nombre, 2)) FROM fabricante;
SELECT nombre, ROUND(precio, 2) FROM producto;
SELECT nombre, TRUNCATE(precio, 0) FROM producto;
SELECT codigo_fabricante FROM producto;
SELECT DISTINCT codigo_fabricante FROM producto;
SELECT nombre FROM fabricante ORDER BY nombre;
SELECT nombre FROM fabricante ORDER BY nombre DESC;
SELECT * FROM producto ORDER BY nombre ASC, precio DESC;
SELECT * FROM fabricante LIMIT 5;
SELECT * FROM fabricante LIMIT 2 OFFSET 3;
SELECT nombre, precio FROM producto ORDER BY precio LIMIT 1;
SELECT nombre, precio FROM producto ORDER BY precio DESC LIMIT 1;
SELECT nombre FROM producto WHERE codigo_fabricante = 2;
SELECT p.nombre, p.precio, f.nombre FROM producto AS p JOIN fabricante  AS f ON p.codigo_fabricante = f.codigo;
SELECT p.nombre, p.precio, f.nombre FROM producto AS p JOIN fabricante  AS f ON p.codigo_fabricante = f.codigo ORDER BY f.nombre;
SELECT p.nombre, p.precio, p.codigo_fabricante, f.nombre FROM producto AS p JOIN fabricante  AS f ON p.codigo_fabricante = f.codigo;
SELECT p.nombre, p.precio, f.nombre FROM producto AS p JOIN fabricante  AS f ON p.codigo_fabricante = f.codigo ORDER BY p.precio LIMIT 1;
SELECT p.nombre, p.precio, f.nombre FROM producto AS p JOIN fabricante  AS f ON p.codigo_fabricante = f.codigo ORDER BY p.precio DESC LIMIT 1;
SELECT p.nombre FROM producto AS p JOIN fabricante  AS f ON p.codigo_fabricante = f.codigo WHERE f.nombre = 'Lenovo';
SELECT p.nombre FROM producto AS p JOIN fabricante  AS f ON p.codigo_fabricante = f.codigo WHERE f.nombre = 'Crucial' AND p.precio > 200;
SELECT p.nombre FROM producto AS p JOIN fabricante  AS f ON p.codigo_fabricante = f.codigo WHERE f.nombre = 'Asus' OR f.nombre = 'Hewlett-Packard' OR f.nombre = 'Seagate';
SELECT p.nombre FROM producto AS p JOIN fabricante  AS f ON p.codigo_fabricante = f.codigo WHERE f.nombre IN ('Asus', 'Hewlett-Packard', 'Seagate');
SELECT p.nombre, p.precio FROM producto AS p JOIN fabricante  AS f ON p.codigo_fabricante = f.codigo WHERE RIGHT(f.nombre, 1) = 'e';
SELECT p.nombre, p.precio FROM producto AS p JOIN fabricante  AS f ON p.codigo_fabricante = f.codigo WHERE f.nombre LIKE '%w%';
SELECT p.nombre, p.precio, f.nombre FROM producto AS p JOIN fabricante  AS f ON p.codigo_fabricante = f.codigo WHERE p.precio >= 180 ORDER BY p.precio DESC, p.nombre ASC;
SELECT * FROM fabricante AS f WHERE EXISTS (SELECT 1 FROM producto AS p WHERE p.codigo_fabricante = f.codigo);
SELECT f.*, p.nombre FROM fabricante AS f LEFT OUTER JOIN producto AS p ON f.codigo = p.codigo_fabricante;
SELECT f.*, p.nombre FROM fabricante AS f LEFT OUTER JOIN producto AS p ON f.codigo = p.codigo_fabricante WHERE p.codigo_fabricante IS NULL;
SELECT f.nombre, p.nombre FROM fabricante AS f LEFT OUTER JOIN producto AS p ON f.codigo = p.codigo_fabricante WHERE f.nombre = 'Lenovo';
SELECT * FROM producto WHERE precio = (SELECT MAX(precio) from producto WHERE codigo_fabricante = (SELECT codigo FROM fabricante WHERE nombre = 'Lenovo'));
SELECT nombre FROM producto WHERE precio = (SELECT MAX(precio) from producto WHERE codigo_fabricante = (SELECT codigo FROM fabricante WHERE nombre = 'Lenovo')) AND codigo_fabricante = (SELECT codigo FROM fabricante WHERE nombre = 'Lenovo');
SELECT nombre FROM producto WHERE precio = (SELECT MIN(precio) from producto WHERE codigo_fabricante = (SELECT codigo FROM fabricante WHERE nombre = 'Hewlett-Packard')) AND codigo_fabricante = (SELECT codigo FROM fabricante WHERE nombre = 'Hewlett-Packard');
SELECT nombre FROM producto WHERE precio >= (SELECT MAX(precio) from producto WHERE codigo_fabricante = (SELECT codigo FROM fabricante WHERE nombre = 'Lenovo'));
SELECT nombre FROM producto WHERE precio >= (SELECT AVG(precio) from producto WHERE codigo_fabricante = (SELECT codigo FROM fabricante WHERE nombre = 'Asus')) AND codigo_fabricante = (SELECT codigo FROM fabricante WHERE nombre = 'Asus');